/*
Integration.app API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"time"
)

// checks if the UpdateFlowInstanceDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateFlowInstanceDto{}

// UpdateFlowInstanceDto struct for UpdateFlowInstanceDto
type UpdateFlowInstanceDto struct {
	Name *string `json:"name,omitempty"`
	Parameters map[string]interface{} `json:"parameters,omitempty"`
	Nodes map[string]interface{} `json:"nodes,omitempty"`
	Enabled *bool `json:"enabled,omitempty"`
	ArchivedAt *time.Time `json:"archivedAt,omitempty"`
}

// NewUpdateFlowInstanceDto instantiates a new UpdateFlowInstanceDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateFlowInstanceDto() *UpdateFlowInstanceDto {
	this := UpdateFlowInstanceDto{}
	return &this
}

// NewUpdateFlowInstanceDtoWithDefaults instantiates a new UpdateFlowInstanceDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateFlowInstanceDtoWithDefaults() *UpdateFlowInstanceDto {
	this := UpdateFlowInstanceDto{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdateFlowInstanceDto) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateFlowInstanceDto) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdateFlowInstanceDto) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdateFlowInstanceDto) SetName(v string) {
	o.Name = &v
}

// GetParameters returns the Parameters field value if set, zero value otherwise.
func (o *UpdateFlowInstanceDto) GetParameters() map[string]interface{} {
	if o == nil || IsNil(o.Parameters) {
		var ret map[string]interface{}
		return ret
	}
	return o.Parameters
}

// GetParametersOk returns a tuple with the Parameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateFlowInstanceDto) GetParametersOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Parameters) {
		return map[string]interface{}{}, false
	}
	return o.Parameters, true
}

// HasParameters returns a boolean if a field has been set.
func (o *UpdateFlowInstanceDto) HasParameters() bool {
	if o != nil && !IsNil(o.Parameters) {
		return true
	}

	return false
}

// SetParameters gets a reference to the given map[string]interface{} and assigns it to the Parameters field.
func (o *UpdateFlowInstanceDto) SetParameters(v map[string]interface{}) {
	o.Parameters = v
}

// GetNodes returns the Nodes field value if set, zero value otherwise.
func (o *UpdateFlowInstanceDto) GetNodes() map[string]interface{} {
	if o == nil || IsNil(o.Nodes) {
		var ret map[string]interface{}
		return ret
	}
	return o.Nodes
}

// GetNodesOk returns a tuple with the Nodes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateFlowInstanceDto) GetNodesOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Nodes) {
		return map[string]interface{}{}, false
	}
	return o.Nodes, true
}

// HasNodes returns a boolean if a field has been set.
func (o *UpdateFlowInstanceDto) HasNodes() bool {
	if o != nil && !IsNil(o.Nodes) {
		return true
	}

	return false
}

// SetNodes gets a reference to the given map[string]interface{} and assigns it to the Nodes field.
func (o *UpdateFlowInstanceDto) SetNodes(v map[string]interface{}) {
	o.Nodes = v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *UpdateFlowInstanceDto) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateFlowInstanceDto) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *UpdateFlowInstanceDto) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *UpdateFlowInstanceDto) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetArchivedAt returns the ArchivedAt field value if set, zero value otherwise.
func (o *UpdateFlowInstanceDto) GetArchivedAt() time.Time {
	if o == nil || IsNil(o.ArchivedAt) {
		var ret time.Time
		return ret
	}
	return *o.ArchivedAt
}

// GetArchivedAtOk returns a tuple with the ArchivedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateFlowInstanceDto) GetArchivedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ArchivedAt) {
		return nil, false
	}
	return o.ArchivedAt, true
}

// HasArchivedAt returns a boolean if a field has been set.
func (o *UpdateFlowInstanceDto) HasArchivedAt() bool {
	if o != nil && !IsNil(o.ArchivedAt) {
		return true
	}

	return false
}

// SetArchivedAt gets a reference to the given time.Time and assigns it to the ArchivedAt field.
func (o *UpdateFlowInstanceDto) SetArchivedAt(v time.Time) {
	o.ArchivedAt = &v
}

func (o UpdateFlowInstanceDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateFlowInstanceDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Parameters) {
		toSerialize["parameters"] = o.Parameters
	}
	if !IsNil(o.Nodes) {
		toSerialize["nodes"] = o.Nodes
	}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.ArchivedAt) {
		toSerialize["archivedAt"] = o.ArchivedAt
	}
	return toSerialize, nil
}

type NullableUpdateFlowInstanceDto struct {
	value *UpdateFlowInstanceDto
	isSet bool
}

func (v NullableUpdateFlowInstanceDto) Get() *UpdateFlowInstanceDto {
	return v.value
}

func (v *NullableUpdateFlowInstanceDto) Set(val *UpdateFlowInstanceDto) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateFlowInstanceDto) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateFlowInstanceDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateFlowInstanceDto(val *UpdateFlowInstanceDto) *NullableUpdateFlowInstanceDto {
	return &NullableUpdateFlowInstanceDto{value: val, isSet: true}
}

func (v NullableUpdateFlowInstanceDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateFlowInstanceDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


