/*
Integration Engine API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the UpdateCustomerAsUserDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateCustomerAsUserDto{}

// UpdateCustomerAsUserDto struct for UpdateCustomerAsUserDto
type UpdateCustomerAsUserDto struct {
	Credentials map[string]interface{} `json:"credentials,omitempty"`
}

// NewUpdateCustomerAsUserDto instantiates a new UpdateCustomerAsUserDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateCustomerAsUserDto() *UpdateCustomerAsUserDto {
	this := UpdateCustomerAsUserDto{}
	return &this
}

// NewUpdateCustomerAsUserDtoWithDefaults instantiates a new UpdateCustomerAsUserDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateCustomerAsUserDtoWithDefaults() *UpdateCustomerAsUserDto {
	this := UpdateCustomerAsUserDto{}
	return &this
}

// GetCredentials returns the Credentials field value if set, zero value otherwise.
func (o *UpdateCustomerAsUserDto) GetCredentials() map[string]interface{} {
	if o == nil || IsNil(o.Credentials) {
		var ret map[string]interface{}
		return ret
	}
	return o.Credentials
}

// GetCredentialsOk returns a tuple with the Credentials field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCustomerAsUserDto) GetCredentialsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Credentials) {
		return map[string]interface{}{}, false
	}
	return o.Credentials, true
}

// HasCredentials returns a boolean if a field has been set.
func (o *UpdateCustomerAsUserDto) HasCredentials() bool {
	if o != nil && !IsNil(o.Credentials) {
		return true
	}

	return false
}

// SetCredentials gets a reference to the given map[string]interface{} and assigns it to the Credentials field.
func (o *UpdateCustomerAsUserDto) SetCredentials(v map[string]interface{}) {
	o.Credentials = v
}

func (o UpdateCustomerAsUserDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateCustomerAsUserDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Credentials) {
		toSerialize["credentials"] = o.Credentials
	}
	return toSerialize, nil
}

type NullableUpdateCustomerAsUserDto struct {
	value *UpdateCustomerAsUserDto
	isSet bool
}

func (v NullableUpdateCustomerAsUserDto) Get() *UpdateCustomerAsUserDto {
	return v.value
}

func (v *NullableUpdateCustomerAsUserDto) Set(val *UpdateCustomerAsUserDto) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateCustomerAsUserDto) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateCustomerAsUserDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateCustomerAsUserDto(val *UpdateCustomerAsUserDto) *NullableUpdateCustomerAsUserDto {
	return &NullableUpdateCustomerAsUserDto{value: val, isSet: true}
}

func (v NullableUpdateCustomerAsUserDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateCustomerAsUserDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


