/*
Integration.app API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FieldMappingDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FieldMappingDto{}

// FieldMappingDto struct for FieldMappingDto
type FieldMappingDto struct {
	Id string `json:"id"`
	Key string `json:"key"`
	Name string `json:"name"`
	ArchivedAt *string `json:"archivedAt,omitempty"`
	Customized *bool `json:"customized,omitempty"`
	Revision string `json:"revision"`
	UniversalFieldMappingId *string `json:"universalFieldMappingId,omitempty"`
	UniversalFieldMappingRevision *string `json:"universalFieldMappingRevision,omitempty"`
	IntegrationId *string `json:"integrationId,omitempty"`
	DataSourceKey *string `json:"dataSourceKey,omitempty"`
	DataSourceId *string `json:"dataSourceId,omitempty"`
	AppSchema map[string]interface{} `json:"appSchema,omitempty"`
	Direction *string `json:"direction,omitempty"`
	DefaultImportValue map[string]interface{} `json:"defaultImportValue,omitempty"`
	DefaultExportValue map[string]interface{} `json:"defaultExportValue,omitempty"`
	ExportValue map[string]interface{} `json:"exportValue,omitempty"`
	ImportValue map[string]interface{} `json:"importValue,omitempty"`
	FrozenImportFields map[string]interface{} `json:"frozenImportFields,omitempty"`
	FrozenExportFields map[string]interface{} `json:"frozenExportFields,omitempty"`
	FrozenUnifiedExportFields map[string]interface{} `json:"frozenUnifiedExportFields,omitempty"`
	AppliedToIntegrations []FiledMappingWithIntegrationDto `json:"appliedToIntegrations,omitempty"`
}

type _FieldMappingDto FieldMappingDto

// NewFieldMappingDto instantiates a new FieldMappingDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFieldMappingDto(id string, key string, name string, revision string) *FieldMappingDto {
	this := FieldMappingDto{}
	this.Id = id
	this.Key = key
	this.Name = name
	this.Revision = revision
	return &this
}

// NewFieldMappingDtoWithDefaults instantiates a new FieldMappingDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFieldMappingDtoWithDefaults() *FieldMappingDto {
	this := FieldMappingDto{}
	return &this
}

// GetId returns the Id field value
func (o *FieldMappingDto) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *FieldMappingDto) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *FieldMappingDto) SetId(v string) {
	o.Id = v
}

// GetKey returns the Key field value
func (o *FieldMappingDto) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *FieldMappingDto) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *FieldMappingDto) SetKey(v string) {
	o.Key = v
}

// GetName returns the Name field value
func (o *FieldMappingDto) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *FieldMappingDto) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *FieldMappingDto) SetName(v string) {
	o.Name = v
}

// GetArchivedAt returns the ArchivedAt field value if set, zero value otherwise.
func (o *FieldMappingDto) GetArchivedAt() string {
	if o == nil || IsNil(o.ArchivedAt) {
		var ret string
		return ret
	}
	return *o.ArchivedAt
}

// GetArchivedAtOk returns a tuple with the ArchivedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FieldMappingDto) GetArchivedAtOk() (*string, bool) {
	if o == nil || IsNil(o.ArchivedAt) {
		return nil, false
	}
	return o.ArchivedAt, true
}

// HasArchivedAt returns a boolean if a field has been set.
func (o *FieldMappingDto) HasArchivedAt() bool {
	if o != nil && !IsNil(o.ArchivedAt) {
		return true
	}

	return false
}

// SetArchivedAt gets a reference to the given string and assigns it to the ArchivedAt field.
func (o *FieldMappingDto) SetArchivedAt(v string) {
	o.ArchivedAt = &v
}

// GetCustomized returns the Customized field value if set, zero value otherwise.
func (o *FieldMappingDto) GetCustomized() bool {
	if o == nil || IsNil(o.Customized) {
		var ret bool
		return ret
	}
	return *o.Customized
}

// GetCustomizedOk returns a tuple with the Customized field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FieldMappingDto) GetCustomizedOk() (*bool, bool) {
	if o == nil || IsNil(o.Customized) {
		return nil, false
	}
	return o.Customized, true
}

// HasCustomized returns a boolean if a field has been set.
func (o *FieldMappingDto) HasCustomized() bool {
	if o != nil && !IsNil(o.Customized) {
		return true
	}

	return false
}

// SetCustomized gets a reference to the given bool and assigns it to the Customized field.
func (o *FieldMappingDto) SetCustomized(v bool) {
	o.Customized = &v
}

// GetRevision returns the Revision field value
func (o *FieldMappingDto) GetRevision() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Revision
}

// GetRevisionOk returns a tuple with the Revision field value
// and a boolean to check if the value has been set.
func (o *FieldMappingDto) GetRevisionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Revision, true
}

// SetRevision sets field value
func (o *FieldMappingDto) SetRevision(v string) {
	o.Revision = v
}

// GetUniversalFieldMappingId returns the UniversalFieldMappingId field value if set, zero value otherwise.
func (o *FieldMappingDto) GetUniversalFieldMappingId() string {
	if o == nil || IsNil(o.UniversalFieldMappingId) {
		var ret string
		return ret
	}
	return *o.UniversalFieldMappingId
}

// GetUniversalFieldMappingIdOk returns a tuple with the UniversalFieldMappingId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FieldMappingDto) GetUniversalFieldMappingIdOk() (*string, bool) {
	if o == nil || IsNil(o.UniversalFieldMappingId) {
		return nil, false
	}
	return o.UniversalFieldMappingId, true
}

// HasUniversalFieldMappingId returns a boolean if a field has been set.
func (o *FieldMappingDto) HasUniversalFieldMappingId() bool {
	if o != nil && !IsNil(o.UniversalFieldMappingId) {
		return true
	}

	return false
}

// SetUniversalFieldMappingId gets a reference to the given string and assigns it to the UniversalFieldMappingId field.
func (o *FieldMappingDto) SetUniversalFieldMappingId(v string) {
	o.UniversalFieldMappingId = &v
}

// GetUniversalFieldMappingRevision returns the UniversalFieldMappingRevision field value if set, zero value otherwise.
func (o *FieldMappingDto) GetUniversalFieldMappingRevision() string {
	if o == nil || IsNil(o.UniversalFieldMappingRevision) {
		var ret string
		return ret
	}
	return *o.UniversalFieldMappingRevision
}

// GetUniversalFieldMappingRevisionOk returns a tuple with the UniversalFieldMappingRevision field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FieldMappingDto) GetUniversalFieldMappingRevisionOk() (*string, bool) {
	if o == nil || IsNil(o.UniversalFieldMappingRevision) {
		return nil, false
	}
	return o.UniversalFieldMappingRevision, true
}

// HasUniversalFieldMappingRevision returns a boolean if a field has been set.
func (o *FieldMappingDto) HasUniversalFieldMappingRevision() bool {
	if o != nil && !IsNil(o.UniversalFieldMappingRevision) {
		return true
	}

	return false
}

// SetUniversalFieldMappingRevision gets a reference to the given string and assigns it to the UniversalFieldMappingRevision field.
func (o *FieldMappingDto) SetUniversalFieldMappingRevision(v string) {
	o.UniversalFieldMappingRevision = &v
}

// GetIntegrationId returns the IntegrationId field value if set, zero value otherwise.
func (o *FieldMappingDto) GetIntegrationId() string {
	if o == nil || IsNil(o.IntegrationId) {
		var ret string
		return ret
	}
	return *o.IntegrationId
}

// GetIntegrationIdOk returns a tuple with the IntegrationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FieldMappingDto) GetIntegrationIdOk() (*string, bool) {
	if o == nil || IsNil(o.IntegrationId) {
		return nil, false
	}
	return o.IntegrationId, true
}

// HasIntegrationId returns a boolean if a field has been set.
func (o *FieldMappingDto) HasIntegrationId() bool {
	if o != nil && !IsNil(o.IntegrationId) {
		return true
	}

	return false
}

// SetIntegrationId gets a reference to the given string and assigns it to the IntegrationId field.
func (o *FieldMappingDto) SetIntegrationId(v string) {
	o.IntegrationId = &v
}

// GetDataSourceKey returns the DataSourceKey field value if set, zero value otherwise.
func (o *FieldMappingDto) GetDataSourceKey() string {
	if o == nil || IsNil(o.DataSourceKey) {
		var ret string
		return ret
	}
	return *o.DataSourceKey
}

// GetDataSourceKeyOk returns a tuple with the DataSourceKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FieldMappingDto) GetDataSourceKeyOk() (*string, bool) {
	if o == nil || IsNil(o.DataSourceKey) {
		return nil, false
	}
	return o.DataSourceKey, true
}

// HasDataSourceKey returns a boolean if a field has been set.
func (o *FieldMappingDto) HasDataSourceKey() bool {
	if o != nil && !IsNil(o.DataSourceKey) {
		return true
	}

	return false
}

// SetDataSourceKey gets a reference to the given string and assigns it to the DataSourceKey field.
func (o *FieldMappingDto) SetDataSourceKey(v string) {
	o.DataSourceKey = &v
}

// GetDataSourceId returns the DataSourceId field value if set, zero value otherwise.
func (o *FieldMappingDto) GetDataSourceId() string {
	if o == nil || IsNil(o.DataSourceId) {
		var ret string
		return ret
	}
	return *o.DataSourceId
}

// GetDataSourceIdOk returns a tuple with the DataSourceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FieldMappingDto) GetDataSourceIdOk() (*string, bool) {
	if o == nil || IsNil(o.DataSourceId) {
		return nil, false
	}
	return o.DataSourceId, true
}

// HasDataSourceId returns a boolean if a field has been set.
func (o *FieldMappingDto) HasDataSourceId() bool {
	if o != nil && !IsNil(o.DataSourceId) {
		return true
	}

	return false
}

// SetDataSourceId gets a reference to the given string and assigns it to the DataSourceId field.
func (o *FieldMappingDto) SetDataSourceId(v string) {
	o.DataSourceId = &v
}

// GetAppSchema returns the AppSchema field value if set, zero value otherwise.
func (o *FieldMappingDto) GetAppSchema() map[string]interface{} {
	if o == nil || IsNil(o.AppSchema) {
		var ret map[string]interface{}
		return ret
	}
	return o.AppSchema
}

// GetAppSchemaOk returns a tuple with the AppSchema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FieldMappingDto) GetAppSchemaOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.AppSchema) {
		return map[string]interface{}{}, false
	}
	return o.AppSchema, true
}

// HasAppSchema returns a boolean if a field has been set.
func (o *FieldMappingDto) HasAppSchema() bool {
	if o != nil && !IsNil(o.AppSchema) {
		return true
	}

	return false
}

// SetAppSchema gets a reference to the given map[string]interface{} and assigns it to the AppSchema field.
func (o *FieldMappingDto) SetAppSchema(v map[string]interface{}) {
	o.AppSchema = v
}

// GetDirection returns the Direction field value if set, zero value otherwise.
func (o *FieldMappingDto) GetDirection() string {
	if o == nil || IsNil(o.Direction) {
		var ret string
		return ret
	}
	return *o.Direction
}

// GetDirectionOk returns a tuple with the Direction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FieldMappingDto) GetDirectionOk() (*string, bool) {
	if o == nil || IsNil(o.Direction) {
		return nil, false
	}
	return o.Direction, true
}

// HasDirection returns a boolean if a field has been set.
func (o *FieldMappingDto) HasDirection() bool {
	if o != nil && !IsNil(o.Direction) {
		return true
	}

	return false
}

// SetDirection gets a reference to the given string and assigns it to the Direction field.
func (o *FieldMappingDto) SetDirection(v string) {
	o.Direction = &v
}

// GetDefaultImportValue returns the DefaultImportValue field value if set, zero value otherwise.
func (o *FieldMappingDto) GetDefaultImportValue() map[string]interface{} {
	if o == nil || IsNil(o.DefaultImportValue) {
		var ret map[string]interface{}
		return ret
	}
	return o.DefaultImportValue
}

// GetDefaultImportValueOk returns a tuple with the DefaultImportValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FieldMappingDto) GetDefaultImportValueOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.DefaultImportValue) {
		return map[string]interface{}{}, false
	}
	return o.DefaultImportValue, true
}

// HasDefaultImportValue returns a boolean if a field has been set.
func (o *FieldMappingDto) HasDefaultImportValue() bool {
	if o != nil && !IsNil(o.DefaultImportValue) {
		return true
	}

	return false
}

// SetDefaultImportValue gets a reference to the given map[string]interface{} and assigns it to the DefaultImportValue field.
func (o *FieldMappingDto) SetDefaultImportValue(v map[string]interface{}) {
	o.DefaultImportValue = v
}

// GetDefaultExportValue returns the DefaultExportValue field value if set, zero value otherwise.
func (o *FieldMappingDto) GetDefaultExportValue() map[string]interface{} {
	if o == nil || IsNil(o.DefaultExportValue) {
		var ret map[string]interface{}
		return ret
	}
	return o.DefaultExportValue
}

// GetDefaultExportValueOk returns a tuple with the DefaultExportValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FieldMappingDto) GetDefaultExportValueOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.DefaultExportValue) {
		return map[string]interface{}{}, false
	}
	return o.DefaultExportValue, true
}

// HasDefaultExportValue returns a boolean if a field has been set.
func (o *FieldMappingDto) HasDefaultExportValue() bool {
	if o != nil && !IsNil(o.DefaultExportValue) {
		return true
	}

	return false
}

// SetDefaultExportValue gets a reference to the given map[string]interface{} and assigns it to the DefaultExportValue field.
func (o *FieldMappingDto) SetDefaultExportValue(v map[string]interface{}) {
	o.DefaultExportValue = v
}

// GetExportValue returns the ExportValue field value if set, zero value otherwise.
func (o *FieldMappingDto) GetExportValue() map[string]interface{} {
	if o == nil || IsNil(o.ExportValue) {
		var ret map[string]interface{}
		return ret
	}
	return o.ExportValue
}

// GetExportValueOk returns a tuple with the ExportValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FieldMappingDto) GetExportValueOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.ExportValue) {
		return map[string]interface{}{}, false
	}
	return o.ExportValue, true
}

// HasExportValue returns a boolean if a field has been set.
func (o *FieldMappingDto) HasExportValue() bool {
	if o != nil && !IsNil(o.ExportValue) {
		return true
	}

	return false
}

// SetExportValue gets a reference to the given map[string]interface{} and assigns it to the ExportValue field.
func (o *FieldMappingDto) SetExportValue(v map[string]interface{}) {
	o.ExportValue = v
}

// GetImportValue returns the ImportValue field value if set, zero value otherwise.
func (o *FieldMappingDto) GetImportValue() map[string]interface{} {
	if o == nil || IsNil(o.ImportValue) {
		var ret map[string]interface{}
		return ret
	}
	return o.ImportValue
}

// GetImportValueOk returns a tuple with the ImportValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FieldMappingDto) GetImportValueOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.ImportValue) {
		return map[string]interface{}{}, false
	}
	return o.ImportValue, true
}

// HasImportValue returns a boolean if a field has been set.
func (o *FieldMappingDto) HasImportValue() bool {
	if o != nil && !IsNil(o.ImportValue) {
		return true
	}

	return false
}

// SetImportValue gets a reference to the given map[string]interface{} and assigns it to the ImportValue field.
func (o *FieldMappingDto) SetImportValue(v map[string]interface{}) {
	o.ImportValue = v
}

// GetFrozenImportFields returns the FrozenImportFields field value if set, zero value otherwise.
func (o *FieldMappingDto) GetFrozenImportFields() map[string]interface{} {
	if o == nil || IsNil(o.FrozenImportFields) {
		var ret map[string]interface{}
		return ret
	}
	return o.FrozenImportFields
}

// GetFrozenImportFieldsOk returns a tuple with the FrozenImportFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FieldMappingDto) GetFrozenImportFieldsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.FrozenImportFields) {
		return map[string]interface{}{}, false
	}
	return o.FrozenImportFields, true
}

// HasFrozenImportFields returns a boolean if a field has been set.
func (o *FieldMappingDto) HasFrozenImportFields() bool {
	if o != nil && !IsNil(o.FrozenImportFields) {
		return true
	}

	return false
}

// SetFrozenImportFields gets a reference to the given map[string]interface{} and assigns it to the FrozenImportFields field.
func (o *FieldMappingDto) SetFrozenImportFields(v map[string]interface{}) {
	o.FrozenImportFields = v
}

// GetFrozenExportFields returns the FrozenExportFields field value if set, zero value otherwise.
func (o *FieldMappingDto) GetFrozenExportFields() map[string]interface{} {
	if o == nil || IsNil(o.FrozenExportFields) {
		var ret map[string]interface{}
		return ret
	}
	return o.FrozenExportFields
}

// GetFrozenExportFieldsOk returns a tuple with the FrozenExportFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FieldMappingDto) GetFrozenExportFieldsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.FrozenExportFields) {
		return map[string]interface{}{}, false
	}
	return o.FrozenExportFields, true
}

// HasFrozenExportFields returns a boolean if a field has been set.
func (o *FieldMappingDto) HasFrozenExportFields() bool {
	if o != nil && !IsNil(o.FrozenExportFields) {
		return true
	}

	return false
}

// SetFrozenExportFields gets a reference to the given map[string]interface{} and assigns it to the FrozenExportFields field.
func (o *FieldMappingDto) SetFrozenExportFields(v map[string]interface{}) {
	o.FrozenExportFields = v
}

// GetFrozenUnifiedExportFields returns the FrozenUnifiedExportFields field value if set, zero value otherwise.
func (o *FieldMappingDto) GetFrozenUnifiedExportFields() map[string]interface{} {
	if o == nil || IsNil(o.FrozenUnifiedExportFields) {
		var ret map[string]interface{}
		return ret
	}
	return o.FrozenUnifiedExportFields
}

// GetFrozenUnifiedExportFieldsOk returns a tuple with the FrozenUnifiedExportFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FieldMappingDto) GetFrozenUnifiedExportFieldsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.FrozenUnifiedExportFields) {
		return map[string]interface{}{}, false
	}
	return o.FrozenUnifiedExportFields, true
}

// HasFrozenUnifiedExportFields returns a boolean if a field has been set.
func (o *FieldMappingDto) HasFrozenUnifiedExportFields() bool {
	if o != nil && !IsNil(o.FrozenUnifiedExportFields) {
		return true
	}

	return false
}

// SetFrozenUnifiedExportFields gets a reference to the given map[string]interface{} and assigns it to the FrozenUnifiedExportFields field.
func (o *FieldMappingDto) SetFrozenUnifiedExportFields(v map[string]interface{}) {
	o.FrozenUnifiedExportFields = v
}

// GetAppliedToIntegrations returns the AppliedToIntegrations field value if set, zero value otherwise.
func (o *FieldMappingDto) GetAppliedToIntegrations() []FiledMappingWithIntegrationDto {
	if o == nil || IsNil(o.AppliedToIntegrations) {
		var ret []FiledMappingWithIntegrationDto
		return ret
	}
	return o.AppliedToIntegrations
}

// GetAppliedToIntegrationsOk returns a tuple with the AppliedToIntegrations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FieldMappingDto) GetAppliedToIntegrationsOk() ([]FiledMappingWithIntegrationDto, bool) {
	if o == nil || IsNil(o.AppliedToIntegrations) {
		return nil, false
	}
	return o.AppliedToIntegrations, true
}

// HasAppliedToIntegrations returns a boolean if a field has been set.
func (o *FieldMappingDto) HasAppliedToIntegrations() bool {
	if o != nil && !IsNil(o.AppliedToIntegrations) {
		return true
	}

	return false
}

// SetAppliedToIntegrations gets a reference to the given []FiledMappingWithIntegrationDto and assigns it to the AppliedToIntegrations field.
func (o *FieldMappingDto) SetAppliedToIntegrations(v []FiledMappingWithIntegrationDto) {
	o.AppliedToIntegrations = v
}

func (o FieldMappingDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FieldMappingDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["key"] = o.Key
	toSerialize["name"] = o.Name
	if !IsNil(o.ArchivedAt) {
		toSerialize["archivedAt"] = o.ArchivedAt
	}
	if !IsNil(o.Customized) {
		toSerialize["customized"] = o.Customized
	}
	toSerialize["revision"] = o.Revision
	if !IsNil(o.UniversalFieldMappingId) {
		toSerialize["universalFieldMappingId"] = o.UniversalFieldMappingId
	}
	if !IsNil(o.UniversalFieldMappingRevision) {
		toSerialize["universalFieldMappingRevision"] = o.UniversalFieldMappingRevision
	}
	if !IsNil(o.IntegrationId) {
		toSerialize["integrationId"] = o.IntegrationId
	}
	if !IsNil(o.DataSourceKey) {
		toSerialize["dataSourceKey"] = o.DataSourceKey
	}
	if !IsNil(o.DataSourceId) {
		toSerialize["dataSourceId"] = o.DataSourceId
	}
	if !IsNil(o.AppSchema) {
		toSerialize["appSchema"] = o.AppSchema
	}
	if !IsNil(o.Direction) {
		toSerialize["direction"] = o.Direction
	}
	if !IsNil(o.DefaultImportValue) {
		toSerialize["defaultImportValue"] = o.DefaultImportValue
	}
	if !IsNil(o.DefaultExportValue) {
		toSerialize["defaultExportValue"] = o.DefaultExportValue
	}
	if !IsNil(o.ExportValue) {
		toSerialize["exportValue"] = o.ExportValue
	}
	if !IsNil(o.ImportValue) {
		toSerialize["importValue"] = o.ImportValue
	}
	if !IsNil(o.FrozenImportFields) {
		toSerialize["frozenImportFields"] = o.FrozenImportFields
	}
	if !IsNil(o.FrozenExportFields) {
		toSerialize["frozenExportFields"] = o.FrozenExportFields
	}
	if !IsNil(o.FrozenUnifiedExportFields) {
		toSerialize["frozenUnifiedExportFields"] = o.FrozenUnifiedExportFields
	}
	if !IsNil(o.AppliedToIntegrations) {
		toSerialize["appliedToIntegrations"] = o.AppliedToIntegrations
	}
	return toSerialize, nil
}

func (o *FieldMappingDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"key",
		"name",
		"revision",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFieldMappingDto := _FieldMappingDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFieldMappingDto)

	if err != nil {
		return err
	}

	*o = FieldMappingDto(varFieldMappingDto)

	return err
}

type NullableFieldMappingDto struct {
	value *FieldMappingDto
	isSet bool
}

func (v NullableFieldMappingDto) Get() *FieldMappingDto {
	return v.value
}

func (v *NullableFieldMappingDto) Set(val *FieldMappingDto) {
	v.value = val
	v.isSet = true
}

func (v NullableFieldMappingDto) IsSet() bool {
	return v.isSet
}

func (v *NullableFieldMappingDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFieldMappingDto(val *FieldMappingDto) *NullableFieldMappingDto {
	return &NullableFieldMappingDto{value: val, isSet: true}
}

func (v NullableFieldMappingDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFieldMappingDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


