/*
Integration.app API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApplyToIntegrationsDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplyToIntegrationsDto{}

// ApplyToIntegrationsDto struct for ApplyToIntegrationsDto
type ApplyToIntegrationsDto struct {
	IntegrationKeys []string `json:"integrationKeys"`
}

type _ApplyToIntegrationsDto ApplyToIntegrationsDto

// NewApplyToIntegrationsDto instantiates a new ApplyToIntegrationsDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplyToIntegrationsDto(integrationKeys []string) *ApplyToIntegrationsDto {
	this := ApplyToIntegrationsDto{}
	this.IntegrationKeys = integrationKeys
	return &this
}

// NewApplyToIntegrationsDtoWithDefaults instantiates a new ApplyToIntegrationsDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplyToIntegrationsDtoWithDefaults() *ApplyToIntegrationsDto {
	this := ApplyToIntegrationsDto{}
	return &this
}

// GetIntegrationKeys returns the IntegrationKeys field value
func (o *ApplyToIntegrationsDto) GetIntegrationKeys() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.IntegrationKeys
}

// GetIntegrationKeysOk returns a tuple with the IntegrationKeys field value
// and a boolean to check if the value has been set.
func (o *ApplyToIntegrationsDto) GetIntegrationKeysOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.IntegrationKeys, true
}

// SetIntegrationKeys sets field value
func (o *ApplyToIntegrationsDto) SetIntegrationKeys(v []string) {
	o.IntegrationKeys = v
}

func (o ApplyToIntegrationsDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplyToIntegrationsDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["integrationKeys"] = o.IntegrationKeys
	return toSerialize, nil
}

func (o *ApplyToIntegrationsDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"integrationKeys",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApplyToIntegrationsDto := _ApplyToIntegrationsDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApplyToIntegrationsDto)

	if err != nil {
		return err
	}

	*o = ApplyToIntegrationsDto(varApplyToIntegrationsDto)

	return err
}

type NullableApplyToIntegrationsDto struct {
	value *ApplyToIntegrationsDto
	isSet bool
}

func (v NullableApplyToIntegrationsDto) Get() *ApplyToIntegrationsDto {
	return v.value
}

func (v *NullableApplyToIntegrationsDto) Set(val *ApplyToIntegrationsDto) {
	v.value = val
	v.isSet = true
}

func (v NullableApplyToIntegrationsDto) IsSet() bool {
	return v.isSet
}

func (v *NullableApplyToIntegrationsDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplyToIntegrationsDto(val *ApplyToIntegrationsDto) *NullableApplyToIntegrationsDto {
	return &NullableApplyToIntegrationsDto{value: val, isSet: true}
}

func (v NullableApplyToIntegrationsDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplyToIntegrationsDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


