/*
Integration.app API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ScenariosControllerList200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScenariosControllerList200Response{}

// ScenariosControllerList200Response struct for ScenariosControllerList200Response
type ScenariosControllerList200Response struct {
	Cursor *string `json:"cursor,omitempty"`
	Items []ScenarioDto `json:"items"`
}

type _ScenariosControllerList200Response ScenariosControllerList200Response

// NewScenariosControllerList200Response instantiates a new ScenariosControllerList200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScenariosControllerList200Response(items []ScenarioDto) *ScenariosControllerList200Response {
	this := ScenariosControllerList200Response{}
	this.Items = items
	return &this
}

// NewScenariosControllerList200ResponseWithDefaults instantiates a new ScenariosControllerList200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScenariosControllerList200ResponseWithDefaults() *ScenariosControllerList200Response {
	this := ScenariosControllerList200Response{}
	return &this
}

// GetCursor returns the Cursor field value if set, zero value otherwise.
func (o *ScenariosControllerList200Response) GetCursor() string {
	if o == nil || IsNil(o.Cursor) {
		var ret string
		return ret
	}
	return *o.Cursor
}

// GetCursorOk returns a tuple with the Cursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScenariosControllerList200Response) GetCursorOk() (*string, bool) {
	if o == nil || IsNil(o.Cursor) {
		return nil, false
	}
	return o.Cursor, true
}

// HasCursor returns a boolean if a field has been set.
func (o *ScenariosControllerList200Response) HasCursor() bool {
	if o != nil && !IsNil(o.Cursor) {
		return true
	}

	return false
}

// SetCursor gets a reference to the given string and assigns it to the Cursor field.
func (o *ScenariosControllerList200Response) SetCursor(v string) {
	o.Cursor = &v
}

// GetItems returns the Items field value
func (o *ScenariosControllerList200Response) GetItems() []ScenarioDto {
	if o == nil {
		var ret []ScenarioDto
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *ScenariosControllerList200Response) GetItemsOk() ([]ScenarioDto, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *ScenariosControllerList200Response) SetItems(v []ScenarioDto) {
	o.Items = v
}

func (o ScenariosControllerList200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScenariosControllerList200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Cursor) {
		toSerialize["cursor"] = o.Cursor
	}
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

func (o *ScenariosControllerList200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varScenariosControllerList200Response := _ScenariosControllerList200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varScenariosControllerList200Response)

	if err != nil {
		return err
	}

	*o = ScenariosControllerList200Response(varScenariosControllerList200Response)

	return err
}

type NullableScenariosControllerList200Response struct {
	value *ScenariosControllerList200Response
	isSet bool
}

func (v NullableScenariosControllerList200Response) Get() *ScenariosControllerList200Response {
	return v.value
}

func (v *NullableScenariosControllerList200Response) Set(val *ScenariosControllerList200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableScenariosControllerList200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableScenariosControllerList200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScenariosControllerList200Response(val *ScenariosControllerList200Response) *NullableScenariosControllerList200Response {
	return &NullableScenariosControllerList200Response{value: val, isSet: true}
}

func (v NullableScenariosControllerList200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScenariosControllerList200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


