/*
Integration Engine API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListDataLinkTableInstances200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListDataLinkTableInstances200Response{}

// ListDataLinkTableInstances200Response struct for ListDataLinkTableInstances200Response
type ListDataLinkTableInstances200Response struct {
	Items []DataLinkTableInstanceDto `json:"items"`
	Cursor *string `json:"cursor,omitempty"`
}

type _ListDataLinkTableInstances200Response ListDataLinkTableInstances200Response

// NewListDataLinkTableInstances200Response instantiates a new ListDataLinkTableInstances200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListDataLinkTableInstances200Response(items []DataLinkTableInstanceDto) *ListDataLinkTableInstances200Response {
	this := ListDataLinkTableInstances200Response{}
	this.Items = items
	return &this
}

// NewListDataLinkTableInstances200ResponseWithDefaults instantiates a new ListDataLinkTableInstances200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListDataLinkTableInstances200ResponseWithDefaults() *ListDataLinkTableInstances200Response {
	this := ListDataLinkTableInstances200Response{}
	return &this
}

// GetItems returns the Items field value
func (o *ListDataLinkTableInstances200Response) GetItems() []DataLinkTableInstanceDto {
	if o == nil {
		var ret []DataLinkTableInstanceDto
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *ListDataLinkTableInstances200Response) GetItemsOk() ([]DataLinkTableInstanceDto, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *ListDataLinkTableInstances200Response) SetItems(v []DataLinkTableInstanceDto) {
	o.Items = v
}

// GetCursor returns the Cursor field value if set, zero value otherwise.
func (o *ListDataLinkTableInstances200Response) GetCursor() string {
	if o == nil || IsNil(o.Cursor) {
		var ret string
		return ret
	}
	return *o.Cursor
}

// GetCursorOk returns a tuple with the Cursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListDataLinkTableInstances200Response) GetCursorOk() (*string, bool) {
	if o == nil || IsNil(o.Cursor) {
		return nil, false
	}
	return o.Cursor, true
}

// HasCursor returns a boolean if a field has been set.
func (o *ListDataLinkTableInstances200Response) HasCursor() bool {
	if o != nil && !IsNil(o.Cursor) {
		return true
	}

	return false
}

// SetCursor gets a reference to the given string and assigns it to the Cursor field.
func (o *ListDataLinkTableInstances200Response) SetCursor(v string) {
	o.Cursor = &v
}

func (o ListDataLinkTableInstances200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListDataLinkTableInstances200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	if !IsNil(o.Cursor) {
		toSerialize["cursor"] = o.Cursor
	}
	return toSerialize, nil
}

func (o *ListDataLinkTableInstances200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListDataLinkTableInstances200Response := _ListDataLinkTableInstances200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListDataLinkTableInstances200Response)

	if err != nil {
		return err
	}

	*o = ListDataLinkTableInstances200Response(varListDataLinkTableInstances200Response)

	return err
}

type NullableListDataLinkTableInstances200Response struct {
	value *ListDataLinkTableInstances200Response
	isSet bool
}

func (v NullableListDataLinkTableInstances200Response) Get() *ListDataLinkTableInstances200Response {
	return v.value
}

func (v *NullableListDataLinkTableInstances200Response) Set(val *ListDataLinkTableInstances200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListDataLinkTableInstances200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListDataLinkTableInstances200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListDataLinkTableInstances200Response(val *ListDataLinkTableInstances200Response) *NullableListDataLinkTableInstances200Response {
	return &NullableListDataLinkTableInstances200Response{value: val, isSet: true}
}

func (v NullableListDataLinkTableInstances200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListDataLinkTableInstances200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


